#!/usr/bin/env node
/*
 * Golden test: runs js/refeq.js over every row of tests/reference_cases.csv
 * (generated by the independent Python implementation) and requires pred,
 * LLN, ULN, predicted in native units and z to match within 1e-8.
 *
 * Usage:  node tests/run_golden.js
 * Exit code 0 = pass, 1 = fail. Do not publish the page unless this passes.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const RefEq = require("../js/refeq.js");

const TOL = 1e-8;
const root = path.join(__dirname, "..");
const reg = JSON.parse(fs.readFileSync(path.join(root, "coefficients.json"), "utf8"));
const csv = fs.readFileSync(path.join(__dirname, "reference_cases.csv"), "utf8").trim().split(/\r?\n/);
const head = csv[0].split(",");
const rows = csv.slice(1).map((line) => {
  const v = line.split(",");
  const o = {};
  head.forEach((h, i) => (o[h] = v[i]));
  return o;
});

const fields = [
  ["pred_kpa", "pred_kpa"],
  ["lln_kpa", "lln_kpa"],
  ["uln_kpa", "uln_kpa"],
  ["pred_native", "pred_native"],
  ["z", "z"]
];

let fails = 0;
const maxDiff = Object.fromEntries(fields.map(([k]) => [k, 0]));
const perSet = {};

for (const r of rows) {
  const res = RefEq.score(reg, r.set_id, r.param, {
    sex: r.sex,
    age: +r.age,
    height_m: +r.height_m,
    weight_kg: +r.weight_kg,
    measured: +r.measured_kpa,
    unit: "kPa"
  });
  perSet[r.set_id] = (perSet[r.set_id] || 0) + 1;
  for (const [k, col] of fields) {
    const want = r[col] === "" || r[col] === "NA" ? null : +r[col];
    const got = res[k];
    let bad;
    if (want === null) bad = got !== null;
    else if (got === null) bad = true;
    else {
      const d = Math.abs(got - want);
      if (d > maxDiff[k]) maxDiff[k] = d;
      bad = !(d <= TOL);
    }
    if (bad) {
      fails++;
      if (fails <= 25) {
        console.log(`FAIL ${r.case_id} ${r.set_id} ${r.param} ${k}: got ${got}, want ${want}`);
      }
    }
  }
  if (r.units_native !== res.units_native) {
    fails++;
    console.log(`FAIL ${r.case_id} ${r.set_id} ${r.param} units: got ${res.units_native}, want ${r.units_native}`);
  }
}

// Every parameter row in the registry must be exercised by at least one case.
const covered = new Set(rows.map((r) => r.set_id + "/" + r.param));
const uncovered = [];
for (const s of reg.sets) for (const p of Object.keys(s.parameters)) if (!covered.has(s.id + "/" + p)) uncovered.push(s.id + "/" + p);

console.log(`\nCases: ${rows.length}  (${Object.entries(perSet).map(([k, v]) => k + " " + v).join(", ")})`);
console.log("Max |diff|: " + Object.entries(maxDiff).map(([k, v]) => `${k} ${v.toExponential(2)}`).join(", "));
console.log(`Registry rows without a golden case: ${uncovered.length ? uncovered.join(", ") : "none"}`);
console.log(`Coefficients built: ${reg.built}`);

if (fails || uncovered.length) {
  console.log(`\nRESULT: FAIL (${fails} mismatches, ${uncovered.length} uncovered rows)`);
  process.exit(1);
}
console.log(`\nRESULT: PASS (all ${rows.length} cases within ${TOL})`);
